### ISSUE TITLE
ocelot audit

### ISSUE THREAD

**Issue by shankj3** [level11consulting/orbitalci#38]
Need an `ocelot audit` function that will do all the things i do by hand: 
- query the database for all "active" builds based on timestamps, see if there are any that just failed somehow
- pull up a summary of the last 10 failed builds / last 10 successful builds 
- show active workers & their worker metadata
- check consul for list of active workers, verify against each werker node and flag if there are any inconsistencies 
- check consul for build runtimes, dump that data, flag any builds tht have been "running" for _way_ too long

---
Maybe it can look like `top` or something, where it fills up the screen? idk. Would also be fine with just a nice looking dump of all the data.

**Comment by shankj3** [comment]
also have an `ocelot audit --prune` which will clean up the consul entries leaving only the active ones that are associated with a current werker process.

**Comment by tjtelan** [comment]
This could be provided extra reinforcement around an uncomfortable issue: Vault token expiration for Werkers (but really, for any services using Vault directly)

Configuration details for vault (and all other external dependencies) should be covered through the wiki. However, it seems reasonable that mistakes in configuration could happen. I'm not sure by what mechanism (perhaps through the `ocelot` cli?), but being able to have an admin-user-initiated Vault sanity check (in addition to the logs that already area generated) could have helped identify the root cause of token expiration earlier.

This would be nice for helping keep #171 in check.

**Comment by tjtelan** [comment]
Recharacterizing this issue:

1. Clean up evidence of builds that have been lost in the DB
2. Show global build trends
3. Show active workers by id
4. Clean up stale worker metadata in Consul
5. Clean up evidence of lost builds in Consul

So two of these are cleaning up lost builds, and two are about keeping worker metadata correct. This should eventually be covered by #212

Lost builds are part of what the API redesign will try to solve.

Global build trends are not useful on their own. Sometimes builds fail.
