### ISSUE TITLE
monorepo support

### ISSUE THREAD

**Issue by shankj3** [level11consulting/orbitalci#48]
For monorepos that have multiple services in them (*cough* this one), you may not want to have the entire configuration in the root file. We should have the capability to work like gradle 

**example structure**
- root/
  - [ocelot.yml](https://github.com/shankj3/ocelot/files/2059326/ocelot_root.copy.yml.txt)
  - svc1/
      - [ocelot.yml](https://github.com/shankj3/ocelot/files/2059328/ocelot_svc1.copy.yml.txt)        
      - src/main/java/
  - svc2/
      - [ocelot.yml](https://github.com/shankj3/ocelot/files/2059330/ocelot_svc2.copy.yml.txt)        
      - src/main/java/

In the example above, the root directory ocelot.yml would run first, installing docker and setting global environment variables. either svc1 or svc2 could run next, the important thing being their individual stage order would be preserved.

**Comment by tjtelan** [comment]
I think this is a good start.

I'm not sure how I feel about the lack of reference between the root/ocelot.yml, and the **/ocelot.yml files, but I see that this method would be straightforward for splitting out a large root/ocelot.yml into multiple smaller files.

A thought would be to use some different keywords to the top-level keys (rather than `stages` in both the root, and the node ocelot.yml), kind of like how ansible uses roles and tasks in order to document levels of ordering.

An additional functionality request would be that we can specify that certain services may depend on other stages being run prior, kind of like a makefile, in order to bring some determinism to the  build steps.

**Comment by tjtelan** [comment]
Monorepo workflows are tied tightly to organizations. We should think about this some more so that it is flexible for a variety of different configurations. It is definitely a feature to think about later in the future. Closing for now.
